### ISSUE TITLE
Reconstructing tur.pdtb.tdb corpus

### ISSUE THREAD

**Issue by thomasCM23** [disrpt/sharedtask2021#4]
IndexError: string index out of range while processing the raw corpus, the TDB version is 1.0. Note the development .conllu file gets correctly populated, but not the .tok or .rel.

```
Traceback (most recent call last):
  File "process_underscores.py", line 633, in <module>
    restore_docs(os.sep.join(["..","data","tur.pdtb.tdb"]),docs2text)
  File "process_underscores.py", line 492, in restore_docs
    sent_text += text[i]
IndexError: string index out of range
```

Thank you.

**Comment by amir-zeldes** [comment]
It should be working now, please let us know if you still run into any trouble!
